### PR TITLE
feat: keep exons while converting

### PR DESCRIPTION
**Pull request by FelixMoelder**
The latest versions of arriba comes with a separate script for annotating exons which is really nice.
However, when utilizing the `convert_fusions_to_vcf.sh`-script exon information will be lost in that process.
To preserve exons during conversion I modified the script checking if the `exon_number1` column exists.
In case it does an additional INFO-entry called `EXON` will be appended to the already existing `INFO`-field.

I assumed that if exons are annotated `exon_number1` and `exon_number2` will always be in columns 31 and 32.

### CODE REVIEW

**Comment by suhrig** [comment]
Great idea! Thanks for taking the time to go as far as implementing it! Please give me some time to test the code change on a few samples. It looks good at first glance, but I will run some tests to be sure. If all goes well, I will merge the code.

**Comment by suhrig** [comment]
Sorry for the lack of response. I've been incredibly busy lately. I have not forgotten about your PR and will get to it as soon as my time permits. Please bear with me.

**Comment by johanneskoester** [comment]
Hi @suhrig. Any chance to get this merged soon? If we can be of further help, just let us know.

**Comment by suhrig** [comment]
I have completed the tests, which went fine. I want to make one more addition before merging. I have it in my local copy of the repo, but something came in between before I could commit and push. Sorry about this huge delay. This year has been crazy so far.

**Comment by suhrig** [comment]
It finally happened! Thank you for the patience!

**Comment by johanneskoester** [comment]
Thanks a lot! Any chance to get a new release?

**Comment by suhrig** [comment]
I haven't been able to work much on Arriba since the last release in February. Therefore, there aren't many big improvements which would be worth releasing (which is quite a bit of effort, so I'd rather do it only when justified). The next release is probably still a few months away. Sorry.

**Comment by johanneskoester** [comment]
With all the projects I maintain (Snakemake, Bioconda, Varlociraptor, ...) we use release-please from Google. It is a very neat github action that automatically composes a change log from conventional commit messages and auto-generates a release. If it helps, I'd be happy to provide a PR here that gets this up an running.

**Comment by johanneskoester** [comment]
For me, making a new release is since then just a matter of hitting the merge button of an autogenerated release-please pull request.

**Comment by johanneskoester** [comment]
https://github.com/google-github-actions/release-please-action

**Comment by suhrig** [comment]
Thank you for the good hint. I should check this out. What consumes most time is not the release on GitHub, however, but all the integrations (Docker, Singularity, Bioconda, mkdocs/readthedocs) as well as testing on real-life samples - which requires lots of CPU. These are rather CI-type-of tasks. I used to have some of the integrations automated, but the interfaces changed over the years and I got tired of having to adapt my scripts.

**Pull request merged**
